# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65d7ec5abcf80897ae52591229a740dbd6a65a91275e4522d0f1b76fbfcf2b0be84282e2ce5cd9846ced54ed4081e7ea285382ddb4e2a44c7eab009309406a5

test:
  secret_key_base: a333add73289b1a306085ec493cb4b3ba4e050f17755b1066f3935d4fa5e66b21bdc0fcf1186ad148f4b9ba076f62c762652d0a5a39e33e3d85827664a4ae773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
